
CREATE TABLE COURSE(COURSE_NAME CHAR(20),COURSE_ID VARCHAR(5),FEES INT);

INSERT INTO COURSE VALUES('JAVA','C1',3000);
INSERT INTO COURSE VALUES('COA','C2',2000);
INSERT INTO COURSE VALUES('TOC','C3',2500);
INSERT INTO COURSE VALUES('CTM','C4',3000);
INSERT INTO COURSE VALUES('DBMS','C5',4000);

ALTER TABLE COURSE ADD DURATION VARCHAR(20);

SELECT * FROM COURSE;

UPDATE COURSE SET DURATION = '3 MONTH' WHERE COURSE_ID = 'C1';
UPDATE COURSE SET DURATION = '2 MONTH' WHERE COURSE_ID = 'C2';
UPDATE COURSE SET DURATION = '4 MONTH' WHERE COURSE_ID = 'C3';
UPDATE COURSE SET DURATION = '3 MONTH' WHERE COURSE_ID = 'C4';
UPDATE COURSE SET DURATION = '2 MONTH' WHERE COURSE_ID = 'C5';

DELETE FROM COURSE WHERE COURSE_ID = 'C5';

TRUNCATE TABLE COURSE;

DROP TABLE COURSE;